- id: doi:10.1186/s13073-022-01141-8
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13073-022-01141-8/MediaObjects/13073_2022_1141_Fig1_HTML.png?as=webp
  extra-links:
    - type: journal
      link: https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-022-01141-8
    - type: source
      link: https://github.com/epifluidlab/cragr
      text: CRAG source code
  tags:
    - Computational Methods
    - EpiFluidLab

- id: doi:10.1038/s41416-021-01635-z
  image: https://media.springernature.com/full/nature-cms/uploads/product/bjc/header-76ac17391903a21e28f15ff5df31f5fa.svg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41416-021-01635-z
  tags:
    - Review
    - EpiFluidLab

- id: doi:10.1101/2022.03.29.486102
  image: https://www.biorxiv.org/content/biorxiv/early/2022/03/30/2022.03.29.486102/F1.medium.gif
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2022.03.29.486102v1.full
    - type: source
      link: https://bitbucket.org/dnaase/bisulfitehic/src/master/
  tags:
    - Experimental Methods
    - Preprint
    - EpiFluidLab

- id: doi:10.1093/bioinformatics/btaa999
  image: https://academic.oup.com/view-large/figure/291832836/btaa999f1.tif
  extra-links:
    - type: journal
      link: https://academic.oup.com/bioinformatics/article/37/16/2502/6015114
    - type: website
      link: http://finaledb.research.cchmc.org/
      text: Database website
    - type: source
      link: https://github.com/epifluidlab/finaledb_portal
      text: FinaleDB source code
    - type: source
      link: https://github.com/epifluidlab/finaledb_workflow
      text: FinaleDB source code for the computational pipeline
  tags:
    - Computational Methods
    - EpiFluidLab

- id: doi:10.1038/s41586-020-2449-8
  image: https://media.springernature.com/w580h326/nature-cms/uploads/collections/NSUP_Cov1-8a789cb352586f4994750d169523aa03.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41586-020-2449-8
  tags:
    - Consortium Paper

- id: doi:10.1038/s41586-020-2493-4
  image: https://media.springernature.com/w580h326/nature-cms/uploads/collections/NSUP_Cov1-8a789cb352586f4994750d169523aa03.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41586-020-2493-4
  tags:
    - Consortium Paper

- id: doi:10.1186/s12885-019-6003-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12885-019-6003-8/MediaObjects/12885_2019_6003_Fig1_HTML.png?as=webp
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1186/s12885-019-6003-8
  tags:
    - Computational Methods
    - Data Analysis

- id: doi:10.1038/s41592-019-0502-z
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41592-019-0502-z/MediaObjects/41592_2019_502_Fig3_HTML.png?as=webp
  extra-links:
    - type: journal
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6765429/
    - type: source
      link: https://bitbucket.org/dnaase/bisulfitehic/src/master
      text: Bhmem source code
  tags:
    - Experimental Methods
    - EpiFluidLab

- id: doi:10.1101/564773
  image: https://www.biorxiv.org/content/biorxiv/early/2019/10/23/564773/F2.medium.gif
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/564773v3.full
  tags:
    - Computational Methods
    - Preprint
    - EpiFluidLab


- id: doi:10.1038/s41588-018-0154-4
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41588-018-0154-4/MediaObjects/41588_2018_154_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41588-018-0154-4
  tags:
    - Consortium Paper

- id: doi:10.1038/s41467-018-03621-1
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-018-03621-1/MediaObjects/41467_2018_3621_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41467-018-03621-1
  tags:
    - Consortium Paper

- id: doi:10.1038/ng.3981
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fng.3981/MediaObjects/41588_2017_Article_BFng3981_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/ng.3981
  tags:
    - Consortium Paper

- id: doi:10.1186/s13059-017-1308-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13059-017-1308-x/MediaObjects/13059_2017_1308_Fig1_HTML.gif?as=webp
  extra-links:
    - type: journal
      link: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1308-x
    - type: source
      link: https://github.com/dnaase/Bis-tools/tree/master/recombination_valley_paper
      text: Recombination valley source code
  tags:
    - Data Analysis
    - EpiFluidLab

- id: doi:10.1101/gr.216754.116
  image: https://genome.cshlp.org/content/genome/27/11/1859/F1.small.gif
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/genome/27/11/1859.full.html
  tags:
    - Consortium Paper

- id: doi:10.1101/gr.216721.116
  image: https://genome.cshlp.org/content/27/11/1843/F1.small.gif
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/27/11/1843.full
  tags:
    - Consortium Paper

- id: doi:10.1093/hmg/ddx312
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/hmg/26/21/10.1093_hmg_ddx312/1/m_ddx312f1.jpeg?Expires=1663343697&Signature=bSZvvC-a6v8oZdZukWeXX-oBGsl7ebIPl5gj44azMiX7SSfl652rHmkCg7vdqJzT-Z9E84XzQcoxtDxRUGk7nX8VUnVtfKkl0IIsIjI2sUosRaU3c9IBPKInJQ-X92nE0VYhtRWeFbwA0iKR0VTSvcXLquDFKouiOnpj8eSQXxzCRqA6uVJPvoXujLvbWKb5hEBTL-gOEQuyUgW-dvs3GgyLqxoBysitxSN1mrgevktjxOkcdzKRlWdFjHa5f3JapIWxAkV~5oH3XO134B1Hs6rkvJ-r1u9l~7Oi03PeMLOeNNL3yxw4TL8hqlVQfKmuYuMWQxs669w~2CVH2rLpwA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  extra-links:
    - type: journal
      link: https://academic.oup.com/hmg/article/26/21/4231/4072616

- id: doi:10.1038/nature24277
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnature24277/MediaObjects/41586_2017_Article_BFnature24277_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24277
  tags:
    - Consortium Paper

- id: doi:10.1038/ng.3969
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fng.3969/MediaObjects/41588_2017_Article_BFng3969_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/ng.3969
  tags:
    - Consortium Paper

- id: doi:10.1038/nature24267
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnature24267/MediaObjects/41586_2017_Article_BFnature24267_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24267?sf121330069=1
  tags:
    - Consortium Paper

- id: doi:10.1038/nature24265
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnature24265/MediaObjects/41586_2017_Article_BFnature24265_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24265?sf122377809=1
  tags:
    - Consortium Paper

- id: doi:10.1038/nature24041
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnature24041/MediaObjects/41586_2017_Article_BFnature24041_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24041
  tags:
    - Consortium Paper

- id: doi:10.1007/s12263-015-0461-7
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs12263-015-0461-7/MediaObjects/12263_2015_461_Fig1_HTML.gif?as=webp
  extra-links:
    - type: journal
      link: https://genesandnutrition.biomedcentral.com/articles/10.1007/s12263-015-0461-7

- id: doi:10.1101/gr.183368.114
  image: https://genome.cshlp.org/content/25/4/467/F1.small.gif
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/25/4/467.full
    - type: source
      link: https://github.com/dnaase/Bis-tools
      text: Source code
  tags:
    - Data Analysis
    - EpiFluidLab

- id: doi:10.1038/nature14248
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnature14248/MediaObjects/41586_2015_Article_BFnature14248_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature14248
  tags:
    - Consortium Paper

- id: doi:10.1101/gr.143008.112
  image: https://genome.cshlp.org/content/22/12/2497/F1.small.gif
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/22/12/2497.full
    - type: source
      link: http://sourceforge.net/projects/uecgatk/
      text: Source code
  tags:
    - Experimental Methods
    - EpiFluidLab

- id: doi:10.1186/gb-2012-13-7-r61
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fgb-2012-13-7-r61/MediaObjects/13059_2012_Article_2899_Fig2_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-7-r61
    - type: source
      link: https://people.csail.mit.edu/dnaase/bissnp2011/
      text: Source code
  tags:
    - Computational Methods
    - EpiFluidLab

- id: doi:10.1038/ng.969
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fng.969/MediaObjects/41588_2012_Article_BFng969_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/ng.969

- id: doi:10.1186/gb-2009-10-7-r78
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fgb-2009-10-7-r78/MediaObjects/13059_2009_Article_2228_Fig1_HTML.jpg?as=webp
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1186/gb-2009-10-7-r78

- id: doi:10.1016/j.jhep.2008.10.034
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0168827809X00048-cov200h.gif
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/abs/pii/S0168827808008052





