

- id: doi:10.1038/s41467-024-47196-6
  image: https://pbs.twimg.com/profile_images/1646627433406234626/v4sbOpgS_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41467-024-47196-6
    - type: source
      link: https://github.com/epifluidlab/FinaleMe.git
      text: FinaleMe source code
    - type: source
      link: https://doi.org/10.5281/zenodo.7647046/
      text: Dataset
  tags:
    - Computational Methods
    - EpiFluidLab

- id: doi:10.1681/ASN.0000000000000324
  image: https://pbs.twimg.com/profile_images/1359929276468850691/Wm_i6aye_400x400.png
  extra-links:
    - type: journal
      link: https://journals.lww.com/jasn/abstract/9900/reduced_nephron_endowment_in_six2_tgctg_mice_is.267.aspx
  tags:
    - Collaboration Paper
    - Data Analysis

- id: doi:10.1093/nar/gkae054
  image: https://pbs.twimg.com/profile_images/1618289430397059072/hMky-2pg_400x400.jpg
  extra-links:
    - type: journal
      link: https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae054/7596006
  tags:
    - Collaboration Paper
    - Data Analysis

- id: doi:10.1038/s41586-022-05487-2
  image: https://pbs.twimg.com/profile_images/1393206230152327170/QnzohDIu_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41586-022-05487-2
  tags:
    - Collaboration Paper
    - Data Analysis

- id: doi:10.1186/s13073-022-01141-8
  image: https://pbs.twimg.com/profile_images/917703818393026560/fMAmjsCL_400x400.jpg
  extra-links:
    - type: journal
      link: https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-022-01141-8
    - type: source
      link: https://github.com/epifluidlab/cragr
      text: CRAG source code
  tags:
    - Computational Methods
    - EpiFluidLab

- id: doi:10.1038/s41416-021-01635-z
  image: https://pbs.twimg.com/profile_images/976501655700205568/rUQ4i5G2_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41416-021-01635-z
  tags:
    - Review
    - EpiFluidLab

- id: doi:10.1186/s13059-023-02889-x
  image: https://pbs.twimg.com/profile_images/917700997350346752/Hv2vqWsQ_400x400.jpg
  extra-links:
    - type: journal
      link: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02889-x
    - type: source
      link: https://bitbucket.org/dnaase/bisulfitehic/src/master/
  tags:
    - Experimental Methods
    - EpiFluidLab

- id: doi:10.1093/bioinformatics/btaa999
  image: https://pbs.twimg.com/profile_images/1054455117603368961/f_s-MzVI_400x400.jpg
  extra-links:
    - type: journal
      link: https://academic.oup.com/bioinformatics/article/37/16/2502/6015114
    - type: website
      link: http://finaledb.research.cchmc.org/
      text: Database website
    - type: source
      link: https://github.com/epifluidlab/finaledb_portal
      text: FinaleDB source code
    - type: source
      link: https://github.com/epifluidlab/finaledb_workflow
      text: FinaleDB source code for the computational pipeline
  tags:
    - Computational Methods
    - EpiFluidLab

- id: doi:10.1038/s41586-020-2449-8
  image: https://media.springernature.com/w580h326/nature-cms/uploads/collections/NSUP_Cov1-8a789cb352586f4994750d169523aa03.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41586-020-2449-8
  tags:
    - Consortium Paper

- id: doi:10.1038/s41586-020-2493-4
  image: https://media.springernature.com/w580h326/nature-cms/uploads/collections/NSUP_Cov1-8a789cb352586f4994750d169523aa03.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41586-020-2493-4
  tags:
    - Consortium Paper

- id: doi:10.1186/s12885-019-6003-8
  image: https://www.cancerherbal.com/wp-content/uploads/2010/04/BMC-Cancer-Journal.png
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1186/s12885-019-6003-8
  tags:
    - Computational Methods
    - Data Analysis

- id: doi:10.1038/s41592-019-0502-z
  image: https://pbs.twimg.com/profile_images/1199341895035449350/v6O3SxS2_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6765429/
    - type: source
      link: https://bitbucket.org/dnaase/bisulfitehic/src/master
      text: Bhmem source code
  tags:
    - Experimental Methods
    - EpiFluidLab

- id: doi:10.1101/564773
  image: https://pbs.twimg.com/card_img/1697420284435849216/thxC6Z8z?format=png&name=360x360
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/564773v3.full
  tags:
    - Computational Methods
    - Preprint
    - EpiFluidLab


- id: doi:10.1038/s41588-018-0154-4
  image: https://pbs.twimg.com/profile_images/1186995531345739777/WXolsdoI_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41588-018-0154-4
  tags:
    - Consortium Paper

- id: doi:10.1038/s41467-018-03621-1
  image: https://pbs.twimg.com/profile_images/1646627433406234626/v4sbOpgS_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/s41467-018-03621-1
  tags:
    - Consortium Paper

- id: doi:10.1038/ng.3981
  image: https://pbs.twimg.com/profile_images/1186995531345739777/WXolsdoI_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/ng.3981
  tags:
    - Consortium Paper

- id: doi:10.1186/s13059-017-1308-x
  image: https://pbs.twimg.com/profile_images/917700997350346752/Hv2vqWsQ_400x400.jpg
  extra-links:
    - type: journal
      link: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1308-x
    - type: source
      link: https://github.com/dnaase/Bis-tools/tree/master/recombination_valley_paper
      text: Recombination valley source code
  tags:
    - Data Analysis

- id: doi:10.1101/gr.216754.116
  image: https://pbs.twimg.com/profile_images/1122921507338895361/ZlthcxIL_400x400.jpg
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/genome/27/11/1859.full.html
  tags:
    - Consortium Paper

- id: doi:10.1101/gr.216721.116
  image: https://pbs.twimg.com/profile_images/1122921507338895361/ZlthcxIL_400x400.jpg
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/27/11/1843.full
  tags:
    - Consortium Paper

- id: doi:10.1093/hmg/ddx312
  image: https://pbs.twimg.com/profile_images/1090628956167045121/Afe4Dg4j_400x400.jpg
  extra-links:
    - type: journal
      link: https://academic.oup.com/hmg/article/26/21/4231/4072616
  tags:
    - Collaboration Paper

- id: doi:10.1038/nature24277
  image: https://pbs.twimg.com/profile_images/1393206230152327170/QnzohDIu_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24277
  tags:
    - Consortium Paper

- id: doi:10.1038/ng.3969
  image: https://pbs.twimg.com/profile_images/1186995531345739777/WXolsdoI_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/ng.3969
  tags:
    - Consortium Paper

- id: doi:10.1038/nature24267
  image: https://pbs.twimg.com/profile_images/1393206230152327170/QnzohDIu_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24267?sf121330069=1
  tags:
    - Consortium Paper

- id: doi:10.1038/nature24265
  image: https://pbs.twimg.com/profile_images/1393206230152327170/QnzohDIu_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24265?sf122377809=1
  tags:
    - Consortium Paper

- id: doi:10.1038/nature24041
  image: https://pbs.twimg.com/profile_images/1393206230152327170/QnzohDIu_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature24041
  tags:
    - Consortium Paper

- id: doi:10.1007/s12263-015-0461-7
  image: https://media.springernature.com/w110/springer-static/cover/journal/12263.jpg
  extra-links:
    - type: journal
      link: https://genesandnutrition.biomedcentral.com/articles/10.1007/s12263-015-0461-7
  tags:
    - Collaboration Paper
    - Data Analysis

- id: doi:10.1101/gr.183368.114
  image: https://pbs.twimg.com/profile_images/1122921507338895361/ZlthcxIL_400x400.jpg
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/25/4/467.full
    - type: source
      link: https://github.com/dnaase/Bis-tools
      text: Source code
  tags:
    - Data Analysis

- id: doi:10.1038/nature14248
  image: https://pbs.twimg.com/profile_images/1393206230152327170/QnzohDIu_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/nature14248
  tags:
    - Consortium Paper

- id: doi:10.1101/gr.143008.112
  image: https://pbs.twimg.com/profile_images/1122921507338895361/ZlthcxIL_400x400.jpg
  extra-links:
    - type: journal
      link: https://genome.cshlp.org/content/22/12/2497.full
    - type: source
      link: http://sourceforge.net/projects/uecgatk/
      text: Source code
  tags:
    - Experimental Methods

- id: doi:10.1186/gb-2012-13-7-r61
  image: https://pbs.twimg.com/profile_images/917700997350346752/Hv2vqWsQ_400x400.jpg
  extra-links:
    - type: journal
      link: https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-7-r61
    - type: source
      link: https://people.csail.mit.edu/dnaase/bissnp2011/
      text: Source code
  tags:
    - Computational Methods

- id: doi:10.1038/ng.969
  image: https://pbs.twimg.com/profile_images/1186995531345739777/WXolsdoI_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.nature.com/articles/ng.969
  tags:
    - Collaboration Paper
    - Data Analysis

- id: doi:10.1186/gb-2009-10-7-r78
  image: https://pbs.twimg.com/profile_images/917700997350346752/Hv2vqWsQ_400x400.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1186/gb-2009-10-7-r78
  tags:
    - Collaboration Paper
    - Data Analysis

- id: doi:10.1016/j.jhep.2008.10.034
  image: https://pbs.twimg.com/profile_images/930733684763873280/sUImFXl2_400x400.jpg
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/abs/pii/S0168827808008052
  tags:
    - Collaboration Paper
    - Data Analysis





